# Generated by Django 5.2.15 on 2026-06-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FuelStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opis_id", models.IntegerField(db_index=True)),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                ("rack_id", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=4, max_digits=6)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("geohash", models.CharField(db_index=True, max_length=8)),
                (
                    "geocode_source",
                    models.CharField(
                        choices=[
                            ("precise", "Precise"),
                            ("city_centroid", "City centroid"),
                        ],
                        default="precise",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fuel Station",
                "verbose_name_plural": "Fuel Stations",
            },
        ),
    ]
