# Generated by Django 5.2.15 on 2026-06-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fuelstation",
            name="geohash",
            field=models.CharField(db_index=True, max_length=12),
        ),
        migrations.AlterUniqueTogether(
            name="fuelstation",
            unique_together={("name", "city", "state")},
        ),
    ]
